### PR TITLE
Added Component for Reviews Block so others can use it.

### PR DESCRIPTION
**Pull request by elimccoy**
Uses a reviews prop which should be an object passed from firebase. I implemented it this way since there are a couple of different reviews needed to be displayed (All the hall reviews vs just a specific users reviews). This branch can be deleted after.

### CODE REVIEW

**Review by ElsaBeth3238 — APPROVED** [review]
Looks good

**Comment by coder13** [comment]
Shouldn't the ReviewsBlockComponent also be getting used in the ExampleHallPage to reduce code duplication?

**Comment by elimccoy** [comment]
> Shouldn't the ReviewsBlockComponent also be getting used in the ExampleHallPage to reduce code duplication?

I was going to catch up my example hall page edits with master then implement it there so there wont be merge problems

**Comment by coder13** [comment]
Sounds good. 
One last thing though, since we got caught up with warnings, this PR must've introduced some new warnings. If we could get those warnings fixed, we can merge.

**Review by coder13 — APPROVED** [review]

**Pull request merged**
