### PR TITLE
merge for TA demo

### PR DESCRIPTION
**Pull request by cdennelly99**
still working on styling

### CODE REVIEW

**Comment by coder13** [comment]
Don't forget to try to fix all the warnings.
You have a couple regarding missing keys for elements generated from map and some instances of a p tag inside a p tag. The latter can be fixed by removing redundancy in having the card.text which just ends up being a p tag

**Comment by acostana** [comment]
Looks good. Still getting the h5 cannot appear as a descendant of p warning

**Review by ElsaBeth3238 — APPROVED** [review]
Looks great!

**Comment by ElsaBeth3238** [comment]
I did not get a descendant warning

**Review by coder13 — APPROVED** [review]

**Pull request merged**
